name: airbnb_checkin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2 #iniezione
  equatable: ^2.0.5 #object equality
  flutter_bloc: ^8.1.6 #gestire stato con pattern BLoC
  flutter_secure_storage: ^9.2.2 #Memorizarre in un area protetta le info dell'utente
  hydrated_bloc: ^9.1.5 #memorizzare gli stati del cubit (relativo ai messaggi dell'assistenza)
  json_annotation: ^4.8.1 #serializzare e deserializzare gli oggetti
  path_provider: ^2.1.2 #supporto per hydrated_bloc per memorizzare le in info in un path specifico
  pine: ^1.0.3 #helper architecturale
  pinput: ^5.0.0 #inserimento del pin
  copy_with_extension: ^5.0.4 #copy with
  collection: ^1.18.0 #helper per manipolare le collezioni in modo più pratico

  # SUPABASE
  supabase_flutter: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.9
  json_serializable: ^6.7.1 #supporto a build_runner per generare file json
  copy_with_extension_gen: ^5.0.4

flutter:

  uses-material-design: true
